name: Edit Story Integration Tests

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  karma:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Cache node modules
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        env:
          cache-name: cache-node-modules

      # TODO: Remove need for `npm install puppeteer`.
      - name: Install dependencies
        run: |
          npm ci
          npm install puppeteer
        env:
          CI: true
          PUPPETEER_PRODUCT: chrome

      # FIXME: https://github.com/google/web-stories-wp/issues/4364
      - name: Increase max number of file watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Run integration tests
        run: npm run test:karma:edit-story -- --headless --snapshots --viewport=1600:1000 --coverage || npm run test:karma:edit-story:retry-failed -- --headless --snapshots --viewport=1600:1000
        env:
          DISABLE_ERROR_BOUNDARIES: true

      - name: Add files for snapshotting
        run: cp -r __static__ .test_artifacts/karma_snapshots/

      - name: Upload code coverage report
        uses: codecov/codecov-action@v1
        with:
          file: build/logs/karma-coverage/edit-story/lcov.info
          flags: karmatests

      - name: Upload Percy snapshots
        uses: percy/snapshot-action@v0.1.2
        with:
          build-directory: '.test_artifacts/karma_snapshots'
          flags: '--config=percy.config.yml'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        if: github.event.pull_request.draft == false

      - name: Upload CUJ coverage
        uses: actions/upload-artifact@v2
        with:
          name: cuj-coverage-edit-story
          path: build/cuj-coverage-edit-story.md
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  deploy-cuj-coverage:
    name: Deploy CUJ Coverage
    needs: [karma]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download coverage file
        uses: actions/download-artifact@v2
        with:
          name: cuj-coverage-edit-story

      - name: Move file
        run: |
          mkdir -p critical-user-journeys
          rm -rf critical-user-journeys/editor.md
          mv cuj-coverage-edit-story.md critical-user-journeys/editor.md

      - name: Commit updates
        run: |
          git add .
          git status
          git diff --staged --quiet && echo 'No changes to commit; exiting!' && exit 0
          git commit -m "Deploy CUJ coverage for ${{ github.sha }}"
          git pull --no-edit --quiet
          git push origin gh-pages
        env:
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
